name: Feature Pull Request
description: Submit a request for a new feature
title: "[Feature]: "
labels: [feature]
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to contribute! Please fill out the form below."
  - type: input
    id: title
    attributes:
      label: Feature Title
      description: "A concise title for the new feature."
      placeholder: "Add a title for your feature"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: "Please describe the feature you're proposing in detail."
      placeholder: "Provide a detailed description of your feature"
    validations:
      required: true
  - type: checkboxes
    id: changes
    attributes:
      label: Changes included
      description: "Select all the changes your pull request includes."
      options:
        - label: New feature
          required: true
        - label: Breaking changes
        - label: Documentation updates
        - label: Tests
  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: "Select the level of impact this feature has."
      options:
        - label: Low
        - label: Medium
        - label: High
    validations:
      required: true
  - type: markdown
    attributes:
      value: "Please ensure you've gone through our contribution guidelines."
