language: node_js
node_js: 10

jobs:
  include:
    - stage: deploy
      name: "Deploy on github"
      if: branch IN (develop, beta, stable, master)
      script:
        - BRANCH=$TRAVIS_BRANCH bash ./calculate.sh
        - VERSION=$(BRANCH=$TRAVIS_BRANCH bash ./calculate.sh)
        - echo "Version $VERSION"
        - echo "AAAAAAA" > a.txt
        - ls

    - name: "Deploy on NPM"
      if: branch IN (develop, beta, stable, master)
      script:
        - BRANCH=$TRAVIS_BRANCH bash ./calculate.sh
        - VERSION=$(BRANCH=$TRAVIS_BRANCH bash ./calculate.sh)
        - echo "Version $VERSION"
        - cat a.txt
        - ls