name: Private issue
description: Create a private issue for internal usage
title: "[Bug]: "
labels: ["private"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened"
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Versions
      description: What are the components versions?
      placeholder: |
        Skaled: 
        IMA: 
        IMA coontract sc:
        IMA contract mainnet: 
        ...add required versions
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: What is the environment to reproduce this issue?
      placeholder: |
        20 active nodes on the network
        N schains up and running 
        Skale Manager version:
        IMA contract version: 
    validations:
      required: false
  - type: dropdown
    id: migrate-to
    attributes:
      label: In which repositories should be migrated?
      multiple: false
      options:
        - Do not migrate
        - skaled
        - IMA
        - skale-consensus
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
