name: Get linked issues
on:
  pull_request:
    types: [ edited, synchronize, opened, reopened ]

jobs:
  check-linked-issues:
    name: Check if pull request has linked issues
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Linked Issues Action
        uses: kin/gh-action-get-linked-issues@v1.0
        id: linked-issues
        with:
          access-token: "${{ secrets.CROSS_REPO_TOKEN }}"
          
      - name: test
        run: |
          echo ${{ steps.linked-issues.outputs.issues }}
