on:
  issues:
    types: [opened]
    
    
jobs:
  migrate-issue:
    runs-on: ubuntu-latest
    steps:
    - run: |
        - name: Get event keys
          run: |
            echo ${{ github.event.issue.bodyResourcePath }}
