on:
  issues:
    types: [opened, edited]
    
    
jobs:
  migrate-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Issue Forms Body Parser
      id: parse
      uses: zentered/issue-forms-body-parser@v2.0.0
      
    - name: Show parsed payload data
      continue-on-error: true
      env:
        GITHUB_CONTEXT: ${{ steps.parse.outputs.data }}
      run: |
        echo "$GITHUB_CONTEXT"
        #echo "${{ env.GITHUB_CONTEXT }}"
        #echo "logs=$(echo $GITHUB_CONTEXT | jq -r '.["relevant-log-output"].text')" >> $GITHUB_ENV
        echo "logs=$(echo $GITHUB_CONTEXT | jq -r '.["relevant-log-output"].text')" >> $GITHUB_ENV
        echo "aaa: ${{ env.logs }}"
        # echo "${{ env.logs }}";
