on:
  issues:
    types: [opened]
    
    
jobs:
  migrate-issue:
    runs-on: ubuntu-latest
    steps:
    - run: |
        - name: Get event keys
          run: |
            for key in "${!github.event[@]}"; do
              echo "$key"
            done
