on:
  issues:
    types: [opened, edited]
    
    
jobs:
  migrate-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Issue Forms Body Parser
      id: parse
      uses: zentered/issue-forms-body-parser@v2.0.0
      
    - name: Show parsed payload data
      run: |
        echo "logs=$(echo "${{ toJSON(steps.parse.outputs.data) }}" | jq -r '.["relevant-log-output"].text')" >> $GITHUB_ENV
        echo "${{ env.logs }}";
