on:
  issues:
    types: [opened]
    
    
jobs:
  migrate-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Issue Forms Body Parser
      id: parse
      uses: zentered/issue-forms-body-parser@v2.0.0
      
    # Examples on how to use the output
    - name: Show parsed payload data
      run: |
        echo ${{ toJSON(steps.parse.outputs.data) }} | jq -r '.["migrate-to"].text'
