on:
  issues:
    types: [opened]
    
    
jobs:
  migrate-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Parse issue
      id: parse
      uses: onmax/issue-form-parser@v1.4
      with:
        issue_number: ${{ github.event.issue.number }}
    - run: 
        echo ${{ fromJson(steps.parse.outputs.payload)['what-happened'] }}
