on:
  issues:
    types: [opened]
    
    
jobs:
  migrate-issue:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'private')
    steps:
    - run: |
        echo ${{ github.event.issue.id }}
