name: Nightly Tests

on:
  schedule:
    - cron: '25 20 * * *'
  workflow_dispatch:

jobs:
  nightly-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
