name: Build and publish skaled container
on:
  pull_request:
    types: [opened, edited, labeled]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
          
      - name: write name
        env:
          NAME: ${{ github.event.pull_request.title }}
          VERSION: ${{ github.event.pull_request.title }}
          BODY: ${{ github.event.pull_request.body }} 
        run: >
          export RELEASE_BODY="                                
            ## General info                                    
                                                               
            * **Name:** $NAME
                                                               
            * **Version:** $VERSION                 
                                                               
            * **Date:** $(date +'%d.%m.%Y')                    
                                                               
            $BODY          
          "
          &&
          echo "RELEASE_BODY=$RELEASE_BODY" >> $GITHUB_ENV


      - name: Create Release
        id: create_release
        env:
          VERSION: ${{ github.event.pull_request.title }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          RELEASE_BODY: ${{ env.RELEASE_BODY }}
        run: |
          echo $RELEASE_BODY
#         with:
#           tag_name: ${{ env.VERSION }}
#           release_name: ${{ env.VERSION }}
#           draft: false
#           prerelease: true
#           body: ${{ env.RELEASE_BODY }}        
