name: Build and publish
on:
  push:
    branches:
      - stable
      - develop
      - beta


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
      NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Set version and branch
        run: |
          export BRANCH=${GITHUB_REF##*/}
          export VERSION=$( bash ./calculate.sh)
          echo "::set-env name=VERSION::$VERSION"
          echo "::set-env name=BRANCH::$BRANCH"
          echo "Version $VERSION"
      - name: Publish to npm
        run: |
          npm version ${{ env.VERSION }}
          npm publish --access=public --tag ${{ env.BRANCH }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          draft: false
          prerelease: true
