name: Build and publish skaled container
on:
  push
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
          
      - name: write name
        env:
          NAME: aaa
          VERSION: bbb
          BODY: ccc
        run: >
          echo "                                
            ## General info                                    
                                                               
            * **Name:** $NAME
                                                               
            * **Version:** $VERSION                 
                                                               
            * **Date:** $(date +'%d.%m.%Y')                    
                                                               
            $BODY          
          "


      - name: Create Release
        id: create_release
        env:
          VERSION: ${{ github.event.pull_request.title }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          RELEASE_BODY: ${{ env.RELEASE_BODY }}
        run: |
          echo $RELEASE_BODY
#         with:
#           tag_name: ${{ env.VERSION }}
#           release_name: ${{ env.VERSION }}
#           draft: false
#           prerelease: true
#           body: ${{ env.RELEASE_BODY }}        
