name: Example workflow
on: [pull_request]
jobs:
  example:
    name: Example job
    runs-on: ubuntu-latest
    steps:
    - name: Run actions/checkout 
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Run fabiankoestring/body-regex-validator-action
      uses: fabiankoestring/body-regex-validator-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST_PATTERN: '(?i)(\bclose\b)|(\bcloses\b)|(\bclosed\b)|(\bfix\b)|(\bfixes\b)|(\bfixed\b)|(\bresolve\b)|(\bresolves\b)|(\bresolved\b)'
