name: Check if a PR has a valid Issue

on:
  pull_request:
    types: [ edited, synchronize, opened, reopened ]

jobs:
  checker:
    name: PR checker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Issue Validator
        uses: HarshCasper/validate-issues-over-pull-requests@v0.1.1
        id: validator
        with:
          prbody: ${{ github.event.pull_request.body }}
          prurl: ${{ github.event.pull_request.url }}
          
      - name: PR has no valid Issue
        id: check-internal
        if: ${{ steps.validator.outputs.valid == 0 }}
        uses: begedin/variable-regex-extractor-action@v0.2.1
        with:
          pattern: |
            `myVar:([^\s]*)`
            
      - name: Extract variable
        id: extract
        uses: begedin/variable-regex-extractor-action@v0.2.1
        with:
          pattern: |
            `myVar:([^\s]*)`
      - name: On matched
        if: steps.extract.outputs.value == 'matched'
        run: exit 0
      - name: On unmatched
        if: steps.extract.outputs.value != 'matched'
        run: exit 1

