name: Check if a PR has a valid Issue

on:
  pull_request:
    types: [ edited, synchronize, opened, reopened ]

jobs:
  checker:
    name: PR checker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Issue Validator
        uses: HarshCasper/validate-issues-over-pull-requests@v0.1.1
        id: validator
        with:
          prbody: ${{ github.event.pull_request.body }}
          prurl: ${{ github.event.pull_request.url }}
          
      - name: PR has no valid Issue
        uses: fabiankoestring/body-regex-validator-action@master
        if: ${{ steps.validator.outputs.valid == 0 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRNUM: ${{ github.event.pull_request.number }}
          PULL_REQUEST_PATTERN: '^(.*Description.*Changes.*Tests.*)$'
          PULL_REQUEST_COMMENT: 'This is my pr comment template.'
          ISSUE_PATTERN: '^(.*Description.*Behavior.*)$'
          ISSUE_COMMENT: 'This is my issue comment template.'

