name: Check if a PR has a valid Issue

on:
  pull_request:
    types: [ edited, synchronize, opened, reopened ]

jobs:
  checker:
    name: PR checker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Issue Validator
        uses: HarshCasper/validate-issues-over-pull-requests@v0.1.1
        id: validator
        with:
          prbody: ${{ github.event.pull_request.body }}
          prurl: ${{ github.event.pull_request.url }}
          
      - name: PR has no valid Issue
        id: check-internal
        if: ${{ steps.validator.outputs.valid == 0 }}
        uses: actions/variable-regex-extractor-action@v1.1
        with:
          pattern: |
            `internal-support#(\d+)`
            
      - name: On matched
        if: ${{ steps.validator.outputs.valid == '' }}
        run: exit 1

