name: Pull request validation
on:
  pull_request:
    types: [ edited, synchronize, opened, reopened ]

jobs:
  checker:
    name: Check link to the issue
    runs-on: ubuntu-latest

    steps:
      - name: Issue regex check 
        uses: FidelusAleksander/gh-action-regex@v0.2.0
        id: regex
        with:
          regex_pattern: "((?i)close[sd]?|resolve[sd]?|fixe[sd]|fix)+[ ][\\w\\/.-]*#[\\d]+"
          regex_match_type: search
          text: ${{ github.event.pull_request.body }}
