name: Release
on:
  pull_request:
      types: [labeled]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set version and branch
      run: |
        echo AAAA;
    - name: update-pull-request
      uses: kt3k/update-pr-description@v1.0.1
      with:
        pr_body: "**some description**"
        github_token: ${{ secrets.GITHUB_TOKEN }}
