name: Release
on:
  pull_request:
      types: [labeled, edited, synchronized]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Read template
      id: template
      uses: juliangruber/read-file-action@v1
      with:
        path: .github/RELEASE_TEMPLATE.md
    - uses: AsasInnab/pr-body-action@v1
      with:
        body: "${{ steps.template.outputs.content }}"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
