name: Release
on:
  pull_request:
      types: [labeled]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set version and branch
      run: |
        echo AAAA;
