name: Release
on:
  push:
    branches-ignore:
      - develop
  check_run:
    workflows: ["Build and publish skaled container"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo TEST
        
