name: Issue Template Checker

on:
  issues:
    types: [opened, edited]

jobs:
  issue-template-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Verify Issue Template
        run: |
          TEMPLATE_FILE=".github/ISSUE_TEMPLATE.md"
          TEMPLATE_CONTENT="$(cat "$TEMPLATE_FILE")"
          DESCRIPTION="$(jq -r '.issue.body' "$GITHUB_EVENT_PATH")"
          IFS=$'\n'
          for SECTION in $(echo "$TEMPLATE_CONTENT" | grep -E '^## '); do
            SECTION_HEADER="$(echo "$SECTION" | sed 's/^## //')"
            if [ -z "$(echo "$DESCRIPTION" | grep -E '^##'"$SECTION_HEADER"')" ]; then
              echo "Issue description is missing or invalid: $SECTION_HEADER section not found"
              exit 1
            fi
          done
