name: Test
on:
  pull_request:
      types: [closed]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.HOST }}
    steps:
    - uses: actions/checkout@v2
    - name: Set version and branch
      run: |
        export BRANCH=${GITHUB_REF##*/}
        echo $BRANCH
        test $BRANCH = "stable" && export STABLE=true || STABLE=false
        echo "STABLE=$STABLE" >> $GITHUB_ENV
        echo $STABLE
    - name: Publish on npm (stable)
      if: ${{ env.STABLE }} == true
      run: |
        echo BBB
  
    - name: Publish on npm
      if: ${{ env.STABLE }} == false
      run: |
        echo AAA
    
