name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        set /a (%random%*10000/32768) + 1000 > rnd.txt
        ls
        cat rnd.txt

    