name: Test
on: [push, pull_request]

jobs:
  browser-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker run
      run: |
        docker run -d --network testnet -p 8545:8545 -p 8546:8546\
          --name ganache trufflesuite/ganache-cli:v6.8.1-beta.0
    - run: |
        docker ps