name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        get-random -maximum 2000 -minimum 100 > a.txt
        $env:test=20
        bash script.sh
    