name: Test
on:
  pull_request:
    types: [closed]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.HOST }}
    steps:
    - uses: actions/checkout@v2
    - name: Publish on npm
      if: github.ref != 'refs/heads/stable'
      run: |
        echo AAA
    - name: Publish on npm (stable)
      if: github.ref == 'refs/heads/stable'
      run: |
        echo BBB
    
