name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: windows-latest
    env:
      HOST: ${{ secrets.HOST }}
    steps:
    - uses: actions/checkout@v2
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: $HOST
    - run: |
        echo 101101 > a.txt 
        $env:test=cat a.txt
        echo $HOST:$env:test
    