name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: windows-latest
    env:
      HOST: ${{ secrets.HOST }}
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        $check=Test-NetConnection -ComputerName $env:HOST -Port 4468; 
        while ($(Test-NetConnection -ComputerName $env:HOST -Port 4467).tcpTestSucceeded -eq $true) {echo "Setup connection..."; sleep 10}
        echo $?
    
    