on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

jobs:
  functional-tests:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ inputs.version }}
    steps:
    - uses: actions/checkout@v3
      with:
        repository: DmytroNazarenko/hello-world
    - run: | 
        ls -la
        echo ${{ secrets.VERSION }}
