name: Test
on:
  pull_request:
      types: [closed]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.HOST }}
    steps:
    - uses: actions/checkout@v2
    - name: Set version and branch
      run: |
        export BRANCH=${GITHUB_REF##*/}
        ( test $BRANCH = "stable" && export STABLE=true ) || export STABLE=false
        echo "STABLE=$STABLE" >> $GITHUB_ENV
    - name: Publish on npm
      if: not ${{ env.STABLE }}
      run: |
        echo AAA
    - name: Publish on npm (stable)
      if: ${{ env.STABLE }}
      run: |
        echo BBB
    
