name: Test
on:
  pull_request:
      types: [closed]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.HOST }}
    steps:
    - uses: actions/checkout@v2
    - name: Set version and branch
      run: |
        export BRANCH=${GITHUB_REF##*/}
        echo $BRANCH
        test $BRANCH = "stable" && export STABLE=true || export NOT_STABLE=true
        echo "STABLE=$STABLE" >> $GITHUB_ENV
        echo "NOT_STABLE=$NOT_STABLE" >> $GITHUB_ENV
        echo $STABLE
    - name: Publish on npm (stable)
      if: ${{ env.STABLE }}
      run: |
        echo BBB
  
    - name: Publish on npm
      if: ${{ env.NOT_STABLE }}
      run: |
        echo AAA
    
  test2:
    needs: [test]
    runs-on: ubuntu-latest
    name: test-2
    steps:
    - run: | 
        echo AAA
