name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: windows-latest
    env:
      HOST: ${{ secrets.HOST }}
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        $env:PORT=get-random -minimum 1000 -maximum 11000
        $env:PORT > PORT
        echo "aaaa $env:PORT"
    
    