name: Test
on: [push, pull_request]
jobs:
  push_test:
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push'
    strategy:
      matrix:
        node: [10, 12]
        os: [ubuntu-latest, macOS, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node 12
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install dependencies
      run: |
        npm i
  pull_request_test:
    if: github.event_name == 'pull_request'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [10, 12]
        os: [ubuntu-latest, macOS, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node 12
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install dependencies
      run: |
        npm i
    