name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          node: [10, 12]
          os: [ubuntu-latest, macOS, windows-latest]
        max-parallel: 6
      steps:
      - uses: actions/checkout@v2
      - name: Set up Node 12
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          npm i
    