name: Test
on: [push, pull_request]

jobs:
  browser-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: which google-chrome
    - name: Install dependencies
      run: |
        npm i
    - name: Chrome testing
      run: |
        node ./test.js