name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: windows-latest
    env:
      HOST: ${{ secrets.HOST }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Install dependencies
      run: |
        npm i
    - run: |
        npx mocha
    
    