name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      host: ${{ secrets.HOST }}
      s: "http://"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - run: |
        export PORT=$((1000 + RANDOM % 10000))
        E=$s$host:$PORT node test.js

    