name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: windows-latest
    env:
      HOST: ${{ secrets.HOST }}
    steps:
    - uses: actions/checkout@v2
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: $HOST
    - run: |
        $env:test=get-random -minimum 1 -maximum 100
        bash script.sh
        echo $env:test$env:test`:$env:test > e
    - run: |
        $env:t=cat e
        echo $env:t
    
    