name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      host: ${{ secrets.HOST }}
      s: "http://"
    steps:
    - uses: actions/checkout@v2
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: root@$host
    - run: |
        echo 
    - run: |
        export PORT=$((1000 + RANDOM % 10000))
        E=$s$host:$PORT test.js

    